version: "3.4"
services:
  api:
    image: mundipagg-web-api
    ports:
      - "5000:5000"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: any
    networks:
      - webnet
    env_file:
      - .env
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - data-volume:/data
    deploy:
      placement:
        constraints: [node.role == manager]
    command: redis-server --appendonly yes
    networks:
      - webnet
networks:
  webnet:
volumes:
  data-volume:
    name: template-redis